image: alpine/latest
packages:
  - docker
  - nodejs
sources:
  - https://git.sr.ht/~mser/emote-server
environment:
  project: emote-server
  docker_image: mserajnik/emote-server
  docker_username: mserajnik
secrets:
  - 2be455df-9ff9-4803-bf5e-2c65d9d986a5
tasks:
  - skip_if_not_release: |
      cd $project
      git describe --exact-match HEAD || complete-build
  - setup: |
      sudo addgroup $(whoami) docker
      sudo service docker start
  - build: |
      cd $project
      version=$(node -e "console.log(require('./package.json').version)")
      docker build . -t $docker_image:latest -t $docker_image:$version
  - publish: |
      cat ~/.docker-hub-personal-access-token | docker login --username $docker_username --password-stdin
      docker push $docker_image --all-tags
